#!/bin/bash

#cp $1-index.html $2-index.html

# cp 8-index.html 101-index.html

cp styles/6-filters.css styles/$2-filters.css
cp styles/4-common.css styles/$2-common.css
cp styles/3-header.css styles/$2-header.css
cp styles/3-footer.css styles/$2-footer.css
# cp styles/8-places.css styles/101-places.css

echo "Version $2 of files created"
